print(ord("C"))
print(ord("D"))
print("ABC" < "ABD")
print("ABC" > "ABD")
print("ABC" >= "ABD")
print("abc" < "PRS")
print(ord("A"))
print(ord("Ą"))
print(ord("ą"))
print("ABC" < "ABCD")
print("ABC" == "ABC")
print(ord("A"))
print(ord("Ą"))
print(ord("B"))
